name: Build Android APK Otomatis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Membangun Mesin Gradle
      run: gradle wrapper

    - name: Berikan Izin Eksekusi Gradlew
      run: chmod +x gradlew

    - name: Mulai Merakit APK
      run: ./gradlew assembleDebug

    - name: Upload File APK Jadi
      uses: actions/upload-artifact@v4
      with:
        name: Aplikasi-Terjemahan-Komik
        path: app/build/outputs/apk/debug/app-debug.apk
